config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :rsvp
  get 'users/show'
  get 'meetup_groups/members'
  devise_for :users
  resources :meetup_groups do
    resources :joins
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :categories
  get 'categories/new'
 
end

app/models/meetup_group.rb
class MeetupGroup < ApplicationRecord
  has_many :comments
  has_many :joins
  has_many :events
  geocoded_by :location
  after_validation :geocode 

  validates :name, presence: true  
  validates :category_id, presence: true  
  validates :about, presence: true  
end

app/controllers/meetup_groups_controller.rb
class MeetupGroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :members]
  before_action :set_meetup_group, only: [:show, :edit, :update, :destroy]

  # GET /joins
  # GET /joins.json
  def index
    if user_signed_in?
      @meetup_groups = MeetupGroup.where(category_id: params[:id])
    else
      @meetup_groups = MeetupGroup.all
    end
  end

  # GET /joins/1
  # GET /joins/1.json
  def show
    if user_signed_in?
      @joins = Join.where(user_id: current_user.id, meetup_group_id: @meetup_group.id)
     end
      @meetup_groups = MeetupGroup.where(category_id: params[:id])    
      @events = Event.where(meetup_group_id: @meetup_group.id)
      @members = Join.where(meetup_group_id: @meetup_group.id)
   
  end

  def members
    @users = Join.where(meetup_group_id: params[:id])
  end


  # GET /joins/new
  def new
    if user_signed_in?
      @meetup_group = MeetupGroup.new
    end
  end

  # GET /joins/1/edit
  def edit
  end

  # POST /joins
  # POST /joins.json
  def create
    @meetup_group = MeetupGroup.new(meetup_group_params)

    respond_to do |format|
      if @meetup_group.save
        @join = Join.new(:user_id => current_user.id, :meetup_group_id => @meetup_group.id)
        @join.save
        format.html { redirect_to @meetup_group, notice: 'Join was successfully created.' }
        format.json { render :show, status: :created, location: @meetup_group }
      else
        format.html { render :new }
        format.json { render json: @meetup_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joins/1
  # PATCH/PUT /joins/1.json
  def update
    respond_to do |format|
      if @meetup_group.update(meetup_group_params)
        format.html { redirect_to @meetup_group, notice: 'Join was successfully updated.' }
        format.json { render :show, status: :ok, location: @meetup_group }
      else
        format.html { render :edit }
        format.json { render json: @meetup_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joins/1
  # DELETE /joins/1.json
  def destroy
    @meetup_group.destroy
    respond_to do |format|
      format.html { redirect_to meetup_groups_url, notice: 'Join was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meetup_group
      @meetup_group = MeetupGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meetup_group_params
      params.require(:meetup_group).permit(:name, :location, :latitude, :longitude, :category_id, :about, :user_id)
    end




end

app/helpers/meetup_groups_helper.rb
module MeetupGroupsHelper
end

app/views/meetup_groups/_form.html.erb
<div class="container"> 
  <div class="col-sm-8 col-sm-offset-2">
    <h1 class="text-center">New Meetup Group</h1>
    <%= form_for(meetup_group) do |f| %>
      <% if meetup_group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(meetup_group.errors.count, "error") %> prohibited this meetup_group from being saved:</h2>

          <ul>
          <% meetup_group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :name, placeholder: 'name', required: true, label: false, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :location, :id => 'geo-input', class: "form-control" %>
      </div> 

      <div class="field">
        <%= f.collection_select :category_id, Category.order(:name),:id, :name, {}, include_blank: true , class: "form-control" %>        
      </div>

      <div class="field">
        <%= f.text_area :about, placeholder: 'About Your Meetup Group', required: true, label: false, class: "form-control" %>
      </div>

      <div class="field">        
        <%= f.text_field :user_id, :value => current_user.id, type: "hidden" %>         
      </div>

      <div class="actions">
        <%= f.submit  %>
      </div>
    <% end %>
    <%= link_to 'Back', meetup_groups_path %>
  </div>
</div>

app/views/meetup_groups/create_event.html.erb
<%= form_for(meetup_groups_create_event) do |f| %>
  

  <div class="field">
    <%= f.text_field :name, placeholder: 'name', class: "form-control" %>
  </div>

  <div class="field">
    <%= f.text_field :event_sub, placeholder: 'Subject', class: "form-control" %>
  </div>

  <div class="field">
    <%= f.text_field :location, :id => 'geo-input', class: "form-control" %>
  </div> 

  <div class="field">
    <%= f.date_field :start_date,  class: "form-control" %>        
  </div>

  <div class="field">
    <%= f.date_field :end_date,  class: "form-control" %>        
  </div>

  <div class="field">
    <%= f.text_field :price, placeholder: 'Price per person', class: "form-control" %>
  </div>

  <div class="field">
    <%= f.text_field :total_seats, placeholder: 'No.of Seats', class: "form-control" %>
  </div>

  <div class="field">
    <%= f.text_area :about, placeholder: 'About Your Meetup Event', class: "form-control" %>
  </div>

  <div class="field">        
    <%= f.text_field :user_id, :value => current_user.id, type: "hidden" %>         
  </div>

  <div class="field">        
    <%= f.text_field :meetup_group_id, :value => @meetup_group.id, type: "hidden" %>         
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetup_groups/edit.html.erb
<h1>Editing Meetup Group</h1>

<%= render 'form', meetup_group: @meetup_group %>

<%= link_to 'Show', @meetup_group %> |
<%= link_to 'Back', meetup_groups_path %>

app/views/meetup_groups/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">        
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  
      <a class="navbar-brand" href="<%= root_path %>">Meetup</a>        
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class=" video-link medium-paragraph text-center">
        <ul class="nav navbar-nav ">
          <li><a href="meetup_groups/new">CREATE MEETUP</a></li> 
        </ul> 
        <ul class="nav navbar-nav navbar-right">  
          <li><a href="#">HOME</a></li>            
          <% if user_signed_in? %>
            <li><a data-method="delete" href="/users/sign_out">SIGN OUT</a> </li>
            <li><%= link_to "PROFILE" , users_show_path(id: current_user.id) %></li>               
          <% else %>                      
            <li> <a href="/users/sign_in">SIGN IN</a></li>
          <% end %>
        </ul>
      </div> 
    </div>
  </div>         
</nav>

<div class="container">
  <div class="row">
    <h1 class="text-center">Meetup Groups</h1>
    <div class="col-sm-8 col-sm-offset-2 text-center"> 
      <% @meetup_groups.each do |meetup_group| %>
      
        <h3> <%= link_to meetup_group.name, meetup_group_path(meetup_group) %></h3><br>
        <%-#= meetup_group.location -%>   
        <%-#=  meetup_group.about -%>
        <%-#= link_to 'Show', meetup_group -%>
        <%-#= link_to 'Edit', edit_meetup_group_path(meetup_group) -%>
        <%-#= link_to 'Destroy', meetup_group, method: :delete, data: { confirm: 'Are you sure?' } -%>
      
      <% end %>    
    <br>
    <%= link_to 'Create Meetup Group', new_meetup_group_path %><br><br>
    </div>  
  </div>
</div>

app/views/meetup_groups/members.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">        
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  
      <a class="navbar-brand" href="<%= root_path %>">Meetup</a>        
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class=" video-link medium-paragraph text-center">
        <ul class="nav navbar-nav ">          
          <li><%= link_to 'CREATE MEETUP', new_meetup_group_path %> </li> 
        </ul> 
        <ul class="nav navbar-nav navbar-right">          
          <li><%= link_to 'HOME', root_path %></li> 
                     
          <% if user_signed_in? %>

            <li><%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete %> </li>
            <li><%= link_to "PROFILE" , users_show_path(id: current_user.id) %></li>               
          <% else %>                      
            <li><%= link_to 'SIGN IN', new_user_session_path %></li>
          <% end %>
        </ul>
      </div> 
    </div>
  </div>         
</nav>

<div class="container">
  <div class="row">

    <div class="member-heading text-center">
      <h1> MEMBERS </h1>
    </div>

    <div class="col-md-12"> 
      <% @users.each do |user| %>
      <% @member = User.find(user.user_id) %> 
       
        <div class="col-md-4">
        
          <div class="col-md-5">  
            <%= image_tag(@member.avatar.url(:thumb)) %>
          </div>
          <div class="col-md-7"> 
            <h4><%=  link_to @member.name, users_show_path(id: @member.id) %></h4>
            <h5><%= @member.location %></h5>
            <h5>Joined <%= user.created_at.strftime("%B %d, %Y") %>
          </div>

        </div>           
      <% end %>
    </div> 
  </div>
</div> 

app/views/meetup_groups/new.html.erb
<%= render 'form', meetup_group: @meetup_group %>

app/views/meetup_groups/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">        
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  
      <a class="navbar-brand" href="<%= root_path %>">Meetup</a>        
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class=" video-link medium-paragraph text-center">
        <ul class="nav navbar-nav ">
          <li><%= link_to 'CREATE MEETUP', new_meetup_group_path %> </li> 
        </ul> 
        <ul class="nav navbar-nav navbar-right">          
          <li><%= link_to 'HOME', root_path %></li> 
          <li><%= link_to 'MEMBERS', meetup_groups_members_path(id: @meetup_group.id) %></li>           
          <% if user_signed_in? %>
            <% if @joins.present? %>            
              <li><%= link_to 'CREATE EVENT', new_event_path(id: @meetup_group.id) %></li>
            <% end %>
            <li><%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete %> </li>
            <li><%= link_to "PROFILE" , users_show_path(id: current_user.id) %></li>               
          <% else %>                      
            <li><%= link_to 'SIGN IN', new_user_session_path %></li>
          <% end %>
        </ul>
      </div> 
    </div>
  </div>         
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 meetups ">
      <div class="text-center header">
        <h1><%= @meetup_group.name %></h1><br>
        <h6><%= @meetup_group.about %></h6>
      </div>

      <div class="col-sm-6">
        <h4><i class="fa fa-map-marker" ></i> <%= @meetup_group.location %> </h4>
      </div>  

      <div class="col-sm-6">
        <h4>Founded: <%= @meetup_group.created_at.strftime("%B %d, %Y") %></h4>
      </div>

        <% if @joins.present? %>
        <% else %> 

          <%= render "joins/form" %>        
        <% end %>
      <div class="col-md-8 col-md-offset-2 upcoming-events">       
        <h4> Upcoming Events </h4>
      </div>
      <div class="col-md-8 col-md-offset-2">       
        <% @events.each do |event| %>
          <div class="col-md-12 events"> 
            <% if event.start_date > Date.today %>
              <br><h4><%= link_to event.name, event_path(id: event.id) %></h4>
              <h5><%= event.start_date.strftime("%B %d, %Y") %></h5>
              <p><%= event.event_sub %></p>
            <% end %>
          </div>
        <% end %>
      </div>


      <div class="col-md-12">
        <h4><%= @meetup_group.comments.count %> Comments</h4>
        <%= render @meetup_group.comments %>

        <h4>Add a comment:</h4>
        <% if user_signed_in? %>
          <%= render "comments/form" %>
        <% else %>
          <%= link_to 'SIGN IN', new_user_session_path %>
        <% end %>
      </div>

      
      <div class="col-md-12">
        <% if user_signed_in? %>
          <% if @meetup_group.user_id == current_user %>
            <%= link_to 'Edit', edit_meetup_group_path(@meetup_group) %> |
          <% end %>
        <% end %>
        <%= link_to 'Back', meetup_groups_path %>
      </div>
    </div>
  </div>
</div>