config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :rsvp
  get 'users/show'
  get 'meetup_groups/members'
  devise_for :users
  resources :meetup_groups do
    resources :joins
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :categories
  get 'categories/new'
 
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :meetup_group
  has_many :rsvp
  geocoded_by :location
  after_validation :geocode 

  validates :name, presence: true
  validates :event_sub, presence: true
  validates :start_date, presence: true
  validates :about, presence: true  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    if user_signed_in?
      @rsvp = Rsvp.where(user_id: current_user.id, event_id: @event.id)
    end
      @rsvp_users = Rsvp.where(event_id: @event.id)
      @rsvp_count = @rsvp_users.count
  end

  # GET /events/new
  def new   
    @meetup = MeetupGroup.find(params[:id]) 
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @meetup = MeetupGroup.find(@event.meetup_group_id) 
  end



  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :latitude, :longitude, :user_id, :about, :meetup_group_id, :start_date, :end_date, :price, :total_seats, :event_sub)     
    end
end
   

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for(event) do |f| %>
      <% if event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

          <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :name, placeholder: 'name', required: true, label: false, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :event_sub, placeholder: 'Subject', required: true, label: false, class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :location, :id => 'geo-input', class: "form-control" %>
      </div> 

      <div class="field">
        <%= f.date_field :start_date, required: true, label: false,  class: "form-control" %>        
      </div>

      <div class="field">
        <%= f.date_field :end_date,  class: "form-control" %>        
      </div>

      <div class="field">
        <%= f.text_field :price, placeholder: 'Price per person', class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :total_seats, placeholder: 'No.of Seats', class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_area :about, placeholder: 'About Your Meetup Event', required: true, label: false, class: "form-control" %>
      </div>

      <div class="field">        
        <%= f.text_field :user_id, :value => current_user.id, type: "hidden" %>         
      </div>

      <div class="field">        
        <%= f.text_field :meetup_group_id, :value => @meetup.id, type: "hidden" %>         
      </div>



      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">        
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  
      <a class="navbar-brand" href="<%= root_path %>">Meetup</a>        
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class=" video-link medium-paragraph text-center">
        <ul class="nav navbar-nav ">
          <% @meetup = MeetupGroup.find(@event.meetup_group_id)%>
          <li><%= link_to 'CREATE MEETUP', new_meetup_group_path %> </li> 
        </ul> 
        <ul class="nav navbar-nav navbar-right">          
          <li><%= link_to 'HOME', root_path %></li> 
          <li><%= link_to 'MEMBERS', meetup_groups_members_path(id: @meetup.id) %></li>
                     
          <% if user_signed_in? %>

            <li><%= link_to 'SIGN OUT', destroy_user_session_path, method: :delete %> </li>
            <li><%= link_to "PROFILE" , users_show_path(id: current_user.id) %></li>               
          <% else %>                      
            <li><%= link_to 'SIGN IN', new_user_session_path %></li>
          <% end %>
        </ul>
      </div> 
    </div>
  </div>         
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 event-border">
      <div class="text-center ">        
        <h1 class="header"><%= @meetup.name %><h1>
        <h2><%=@event.name %></h2><br>
        <h5><%= @event.event_sub %></h5>
      </div>

      
      <div class="row"> 
        <div class="col-md-6">    
          <h4> <%= @event.start_date.strftime("%B %d, %Y") %> </h4>
          <h4><i class="fa fa-map-marker" ></i> <%= @event.location %> </h4><br>
        </div> 
        <div class="col-md-6">  
          <h4> <%= @event.end_date.strftime("%B %d, %Y") %> </h4><br>
        </div> 

        <div class="col-md-12"> 
          <% if @event.total_seats != ''%>
            <% @balance = @event.total_seats.to_i - @rsvp_count %>            
            <h4> <%= @balance %> Seats Remaining </h4>      
          <% end %>
          <p class="text-center"> <%= @event.about   %> </p><br>
          
          <% if @rsvp.present? %>
            <% @rsvp.each do |rsvp| %>
              <%='Change RSVP'%><br>
              <%= link_to 'Not Going', rsvp_path(id: rsvp.id),  method: :delete %>
            <% end %>
          <% else %>
            <%= link_to 'RSVP', rsvp_index_path(id: @event.id),  method: :post %><br>
          <% end %>
        </div>

        <div class="col-md-12">
          <h5><%= @rsvp_users.count %> Going</h5>
          <br><br><% @rsvp_users.each do |rsvp_user| %>
          <% @user = User.find(rsvp_user.user_id) %>
            <div class="col-md-12">
              <div class="col-md-3">  
                <%= image_tag(@user.avatar.url(:thumb)) %><br><br>
              </div>
              <div class="col-md-9"> 
                <h4><%= @user.name %></h4>
                <h5><%= @user.location %></h5>
              </div>         
            </div>
          <% end %>
        </div>

        <div class="col-md-12">
          <% if user_signed_in? %>
            <% if @event.user_id == current_user.id %>
              <%= link_to 'Edit', edit_event_path(@event) %> |
            <% end %>
          <% end %>
          <%= link_to 'Back', meetup_group_path(@event.meetup_group_id) %>
        </div>


      </div>  
    </div>

  </div>
</div>