config/routes.rb
Rails.application.routes.draw do
  
  resources :events
  resources :rsvp
  get 'users/show'
  get 'meetup_groups/members'
  devise_for :users
  resources :meetup_groups do
    resources :joins
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :categories
  get 'categories/new'
 
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :meetup_group
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_join, only: [:show, :edit, :update, :destroy]

  # GET /joins
  # GET /joins.json
  def index
    @joins = Join.all
  end

  # GET /joins/1
  # GET /joins/1.json
  def show
  end

  # GET /joins/new
  def new
    @join = Join.new
  end

  # GET /joins/1/edit
  def edit
  end

  # POST /joins
  # POST /joins.json
  def create
    @join = Join.new(join_params)

    respond_to do |format|
      if @join.save
        format.html { redirect_to :back, notice: 'Join was successfully created.' }
        format.json { render :show, status: :created, location: @join }
      else
        format.html { render :new }
        format.json { render json: @join.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joins/1
  # PATCH/PUT /joins/1.json
  def update
    respond_to do |format|
      if @join.update(join_params)
        format.html { redirect_to @join, notice: 'Join was successfully updated.' }
        format.json { render :show, status: :ok, location: @join }
      else
        format.html { render :edit }
        format.json { render json: @join.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joins/1
  # DELETE /joins/1.json
  def destroy
    @join.destroy
    respond_to do |format|
      format.html { redirect_to joins_url, notice: 'Join was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_join
      @join = Join.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def join_params
      params.require(:join).permit(:user_id, :meetup_group_id)
    end
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/views/joins/_form.html.erb
<% if user_signed_in? %>
  <%= form_for([@meetup_group, @meetup_group.joins.build]) do |f| %>
    

    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>

    <div class="field">
      <%= f.hidden_field :meetup_group_id, :value => @meetup_group.id %>
    </div>

    <div class="actions">
      <%= f.submit "Join" %>
    </div>
  <% end %>
<% end %>

app/views/joins/edit.html.erb
<h1>Editing Join</h1>

<%= render 'form', join: @join %>

<%= link_to 'Show', @join %> |
<%= link_to 'Back', joins_path %>

app/views/joins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Joins</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Meetup group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @joins.each do |join| %>
      <tr>
        <td><%= join.user_id %></td>
        <td><%= join.meetup_group_id %></td>
        <td><%= link_to 'Show', join %></td>
        <td><%= link_to 'Edit', edit_join_path(join) %></td>
        <td><%= link_to 'Destroy', join, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Join', new_join_path %>

app/views/joins/new.html.erb
<h1>New Join</h1>

<%= render 'form', join: @join %>

<%= link_to 'Back', joins_path %>

app/views/joins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @join.user_id %>
</p>

<p>
  <strong>Meetup group:</strong>
  <%= @join.meetup_group_id %>
</p>

<%= link_to 'Edit', edit_join_path(@join) %> |
<%= link_to 'Back', joins_path %>